### ISSUE TITLE
Kora Grey only shows grey folders in my $HOME

### ISSUE THREAD

**Issue by LordChaos73** [bikass/kora#126]
Hi,

First of all; what a great set of icons! Thank you for your hard work. I've installed these icons on two machines (openSUSE tumbleweed, manually) and on another machine from the AUR repository (kora-icon-theme-git).
When I select the "Kora Grey" theme, my home directory in Doplhin is indeed displaying grey folders, but when I click inside another directory (e.g. documents) then the icons are blue as in the default theme. Let me know if you need additional details.

**Comment by bikass** [comment]
I don't use KDE at the moment. And don't really have time to check on VM. It is fine on gnome - means symlinks are working properly... I will check some day.

**Comment by Vistaus** [comment]
Where do I find the symlinks? Maybe I could try to fix it and do a PR.

**Comment by LordChaos73** [comment]
What DE do you use?

**Comment by Vistaus** [comment]
KDE, just like you.

**Comment by BillyDM** [comment]
This appears to be a bug with KDE itself in how it handles symlinks. A workaround I found is to just replace the contents of `kora/places/scalable` with `kora-pgrey/places/scalable`. Of course this messes up the default theme, but if you only care about the grey folders this solution works.

Of course you can also download the theme from pling https://www.gnome-look.org/p/1256209, but I found *another* KDE bug in that Dolphin doesn't unzip the zip file properly. The solution I found is to use the `unzip` command from the terminal to unzip the file instead of using Dolphin to unzip it.

**Comment by bikass** [comment]
@BillyDM  Yes, I noticed that too. Extracting in Dolphin doesn't work. 
Ok, if tar.xz will fix that problem - I can do that.

**Comment by BillyDM** [comment]
I'm not certain that it will fix the problem, it's just a guess.
